// page 404 is not found

import Head from "next/head";

export default function Page404() {
    return (
        <>
            <Head>
                <title>Portfolio</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <main className="h-[75vh]">

                <section className="ErrorPage">
                    <div className="noise"></div>
                    <div className="overlay"></div>
                    <div className="terminal">
                        <h1 className="text-red-700">Error <span className="text-white">404</span></h1>
                        <p className="output">The page you are looking for might have been removed, had its name changed or
                            is temporarily unavailable.</p>
                        <p className="output">Please return to the <a className="text-red-700" href="#">
                            homepage !</a></p>
                        <p className="output">Have a good day.</p>
                    </div>
                </section>

            </main>
        </>
    )
}

